name = "fitness-checkin"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "fitness-checkin-secret-change-in-production"

[[d1_databases]]
binding = "DB"
database_name = "fitness-checkin-db"
database_id = "3964181f-11b9-4bae-b9bf-fe361e96914b"

main = "functions/api/[[path]].ts"
assets = { directory = "./dist" }

[[routes]]
pattern = "wangmingming.cn/*"
zone_name = "wangmingming.cn"

[[routes]]
pattern = "www.wangmingming.cn/*"
zone_name = "wangmingming.cn"
